/**
 * Catalogue véhicules : marques, modèles et catégories de carrosserie
 * Catégories : citadine | berline | berline_luxe | suv_compact | suv | suv_luxe | sports | supercar | electrique | monospace | utilitaire | cabriolet
 */

export const VEHICLE_CATALOG = {
  // ── FRANCE ───────────────────────────────────────────────────────────────────
  Peugeot: [
    { model: '108',         cat: 'citadine'    },
    { model: '208',         cat: 'citadine'    },
    { model: '2008',        cat: 'suv_compact' },
    { model: '308',         cat: 'berline'     },
    { model: '3008',        cat: 'suv'         },
    { model: '408',         cat: 'berline'     },
    { model: '508',         cat: 'berline_luxe'},
    { model: '5008',        cat: 'suv'         },
    { model: 'Partner',     cat: 'utilitaire'  },
    { model: 'Rifter',      cat: 'monospace'   },
    { model: 'Expert',      cat: 'utilitaire'  },
    { model: 'e-208',       cat: 'electrique'  },
    { model: 'e-2008',      cat: 'electrique'  },
  ],
  Renault: [
    { model: 'Twingo',      cat: 'citadine'    },
    { model: 'Clio',        cat: 'citadine'    },
    { model: 'Clio E-Tech', cat: 'electrique'  },
    { model: 'Captur',      cat: 'suv_compact' },
    { model: 'Megane',      cat: 'berline'     },
    { model: 'Megane E-Tech',cat: 'electrique' },
    { model: 'Kadjar',      cat: 'suv'         },
    { model: 'Scenic',      cat: 'monospace'   },
    { model: 'Grand Scenic',cat: 'monospace'   },
    { model: 'Koleos',      cat: 'suv'         },
    { model: 'Arkana',      cat: 'suv_compact' },
    { model: 'Talisman',    cat: 'berline_luxe'},
    { model: 'Zoe',         cat: 'electrique'  },
    { model: 'Kangoo',      cat: 'utilitaire'  },
    { model: 'Espace',      cat: 'monospace'   },
  ],
  Citroën: [
    { model: 'C1',          cat: 'citadine'    },
    { model: 'C3',          cat: 'citadine'    },
    { model: 'C3 Aircross', cat: 'suv_compact' },
    { model: 'C4',          cat: 'berline'     },
    { model: 'C4 X',        cat: 'berline'     },
    { model: 'C5 Aircross', cat: 'suv'         },
    { model: 'C5 X',        cat: 'berline_luxe'},
    { model: 'Berlingo',    cat: 'utilitaire'  },
    { model: 'SpaceTourer', cat: 'monospace'   },
    { model: 'ë-C4',        cat: 'electrique'  },
    { model: 'Ami',         cat: 'electrique'  },
  ],
  DS: [
    { model: 'DS3',         cat: 'citadine'    },
    { model: 'DS3 Crossback', cat: 'suv_compact'},
    { model: 'DS4',         cat: 'berline'     },
    { model: 'DS7 Crossback', cat: 'suv'       },
    { model: 'DS9',         cat: 'berline_luxe'},
  ],

  // ── ALLEMAGNE ────────────────────────────────────────────────────────────────
  BMW: [
    { model: '116i',        cat: 'berline'     },
    { model: '118i',        cat: 'berline'     },
    { model: '120i',        cat: 'berline'     },
    { model: '220i',        cat: 'berline'     },
    { model: '318i',        cat: 'berline'     },
    { model: '320i',        cat: 'berline'     },
    { model: '320d',        cat: 'berline'     },
    { model: '330i',        cat: 'berline_luxe'},
    { model: '420i',        cat: 'sports'      },
    { model: '430i',        cat: 'sports'      },
    { model: '520d',        cat: 'berline_luxe'},
    { model: '530i',        cat: 'berline_luxe'},
    { model: '730i',        cat: 'berline_luxe'},
    { model: '740i',        cat: 'berline_luxe'},
    { model: 'M2',          cat: 'sports'      },
    { model: 'M3',          cat: 'sports'      },
    { model: 'M4',          cat: 'sports'      },
    { model: 'M5',          cat: 'berline_luxe'},
    { model: 'M8',          cat: 'supercar'    },
    { model: 'X1',          cat: 'suv_compact' },
    { model: 'X2',          cat: 'suv_compact' },
    { model: 'X3',          cat: 'suv'         },
    { model: 'X4',          cat: 'suv'         },
    { model: 'X5',          cat: 'suv_luxe'    },
    { model: 'X6',          cat: 'suv_luxe'    },
    { model: 'X7',          cat: 'suv_luxe'    },
    { model: 'iX',          cat: 'electrique'  },
    { model: 'i4',          cat: 'electrique'  },
    { model: 'i7',          cat: 'electrique'  },
    { model: 'Z4',          cat: 'cabriolet'   },
  ],
  'Mercedes-Benz': [
    { model: 'Classe A',    cat: 'berline'     },
    { model: 'Classe B',    cat: 'monospace'   },
    { model: 'Classe C',    cat: 'berline'     },
    { model: 'Classe E',    cat: 'berline_luxe'},
    { model: 'Classe S',    cat: 'berline_luxe'},
    { model: 'GLA',         cat: 'suv_compact' },
    { model: 'GLB',         cat: 'suv_compact' },
    { model: 'GLC',         cat: 'suv'         },
    { model: 'GLE',         cat: 'suv_luxe'    },
    { model: 'GLS',         cat: 'suv_luxe'    },
    { model: 'AMG GT',      cat: 'supercar'    },
    { model: 'AMG C63',     cat: 'sports'      },
    { model: 'AMG E63',     cat: 'berline_luxe'},
    { model: 'SL',          cat: 'cabriolet'   },
    { model: 'SLC',         cat: 'cabriolet'   },
    { model: 'EQA',         cat: 'electrique'  },
    { model: 'EQB',         cat: 'electrique'  },
    { model: 'EQC',         cat: 'electrique'  },
    { model: 'EQE',         cat: 'electrique'  },
    { model: 'EQS',         cat: 'electrique'  },
    { model: 'CLA',         cat: 'berline'     },
    { model: 'CLS',         cat: 'berline_luxe'},
  ],
  Audi: [
    { model: 'A1',          cat: 'citadine'    },
    { model: 'A3',          cat: 'berline'     },
    { model: 'A4',          cat: 'berline'     },
    { model: 'A5',          cat: 'sports'      },
    { model: 'A6',          cat: 'berline_luxe'},
    { model: 'A7',          cat: 'berline_luxe'},
    { model: 'A8',          cat: 'berline_luxe'},
    { model: 'Q2',          cat: 'suv_compact' },
    { model: 'Q3',          cat: 'suv_compact' },
    { model: 'Q5',          cat: 'suv'         },
    { model: 'Q7',          cat: 'suv_luxe'    },
    { model: 'Q8',          cat: 'suv_luxe'    },
    { model: 'TT',          cat: 'sports'      },
    { model: 'R8',          cat: 'supercar'    },
    { model: 'RS3',         cat: 'sports'      },
    { model: 'RS6',         cat: 'berline_luxe'},
    { model: 'e-tron',      cat: 'electrique'  },
    { model: 'e-tron GT',   cat: 'electrique'  },
    { model: 'Q4 e-tron',   cat: 'electrique'  },
  ],
  Porsche: [
    { model: '911',         cat: 'supercar'    },
    { model: '911 GT3',     cat: 'supercar'    },
    { model: '911 Turbo',   cat: 'supercar'    },
    { model: 'Boxster',     cat: 'cabriolet'   },
    { model: 'Cayman',      cat: 'sports'      },
    { model: 'Panamera',    cat: 'berline_luxe'},
    { model: 'Cayenne',     cat: 'suv_luxe'    },
    { model: 'Cayenne GTS', cat: 'suv_luxe'    },
    { model: 'Cayenne Turbo',cat: 'suv_luxe'   },
    { model: 'Macan',       cat: 'suv'         },
    { model: 'Macan GTS',   cat: 'suv'         },
    { model: 'Taycan',      cat: 'electrique'  },
    { model: 'Taycan Cross Turismo', cat: 'electrique'},
  ],
  Volkswagen: [
    { model: 'Polo',        cat: 'citadine'    },
    { model: 'Golf',        cat: 'berline'     },
    { model: 'Golf GTI',    cat: 'sports'      },
    { model: 'Golf R',      cat: 'sports'      },
    { model: 'Golf Variant',cat: 'berline'     },
    { model: 'T-Cross',     cat: 'suv_compact' },
    { model: 'T-Roc',       cat: 'suv_compact' },
    { model: 'Tiguan',      cat: 'suv'         },
    { model: 'Tiguan Allspace', cat: 'suv'     },
    { model: 'Touareg',     cat: 'suv_luxe'    },
    { model: 'Passat',      cat: 'berline'     },
    { model: 'Arteon',      cat: 'berline_luxe'},
    { model: 'ID.3',        cat: 'electrique'  },
    { model: 'ID.4',        cat: 'electrique'  },
    { model: 'ID.5',        cat: 'electrique'  },
    { model: 'Caddy',       cat: 'utilitaire'  },
    { model: 'Multivan',    cat: 'monospace'   },
  ],
  Opel: [
    { model: 'Corsa',       cat: 'citadine'    },
    { model: 'Astra',       cat: 'berline'     },
    { model: 'Mokka',       cat: 'suv_compact' },
    { model: 'Crossland',   cat: 'suv_compact' },
    { model: 'Grandland',   cat: 'suv'         },
    { model: 'Insignia',    cat: 'berline_luxe'},
    { model: 'Corsa-e',     cat: 'electrique'  },
    { model: 'Mokka-e',     cat: 'electrique'  },
  ],
  SEAT: [
    { model: 'Ibiza',       cat: 'citadine'    },
    { model: 'Leon',        cat: 'berline'     },
    { model: 'Arona',       cat: 'suv_compact' },
    { model: 'Ateca',       cat: 'suv'         },
    { model: 'Tarraco',     cat: 'suv'         },
  ],
  Skoda: [
    { model: 'Fabia',       cat: 'citadine'    },
    { model: 'Octavia',     cat: 'berline'     },
    { model: 'Superb',      cat: 'berline_luxe'},
    { model: 'Kamiq',       cat: 'suv_compact' },
    { model: 'Karoq',       cat: 'suv_compact' },
    { model: 'Kodiaq',      cat: 'suv'         },
    { model: 'Enyaq',       cat: 'electrique'  },
  ],

  // ── ITALIE ───────────────────────────────────────────────────────────────────
  Ferrari: [
    { model: '296 GTB',     cat: 'supercar'    },
    { model: '488 GTB',     cat: 'supercar'    },
    { model: 'F8 Tributo',  cat: 'supercar'    },
    { model: 'SF90 Stradale',cat: 'supercar'   },
    { model: 'Roma',        cat: 'supercar'    },
    { model: 'Portofino',   cat: 'supercar'    },
    { model: 'California T',cat: 'supercar'    },
    { model: 'GTC4Lusso',   cat: 'supercar'    },
    { model: 'Purosangue',  cat: 'supercar'    },
    { model: '812 Superfast',cat: 'supercar'   },
  ],
  Lamborghini: [
    { model: 'Huracán',     cat: 'supercar'    },
    { model: 'Huracán STO', cat: 'supercar'    },
    { model: 'Aventador',   cat: 'supercar'    },
    { model: 'Urus',        cat: 'suv_luxe'    },
  ],
  'Alfa Romeo': [
    { model: 'Giulia',      cat: 'berline'     },
    { model: 'Stelvio',     cat: 'suv'         },
    { model: 'Tonale',      cat: 'suv_compact' },
    { model: '4C',          cat: 'supercar'    },
  ],
  Fiat: [
    { model: '500',         cat: 'citadine'    },
    { model: '500e',        cat: 'electrique'  },
    { model: '500L',        cat: 'monospace'   },
    { model: '500X',        cat: 'suv_compact' },
    { model: 'Panda',       cat: 'citadine'    },
    { model: 'Tipo',        cat: 'berline'     },
  ],
  Maserati: [
    { model: 'Ghibli',      cat: 'berline_luxe'},
    { model: 'Quattroporte',cat: 'berline_luxe'},
    { model: 'Levante',     cat: 'suv_luxe'    },
    { model: 'GranTurismo', cat: 'supercar'    },
    { model: 'Grecale',     cat: 'suv'         },
  ],

  // ── JAPON / CORÉE ────────────────────────────────────────────────────────────
  Toyota: [
    { model: 'Yaris',       cat: 'citadine'    },
    { model: 'Yaris Cross', cat: 'suv_compact' },
    { model: 'Corolla',     cat: 'berline'     },
    { model: 'Corolla Cross',cat: 'suv_compact'},
    { model: 'Camry',       cat: 'berline_luxe'},
    { model: 'RAV4',        cat: 'suv'         },
    { model: 'C-HR',        cat: 'suv_compact' },
    { model: 'Prius',       cat: 'berline'     },
    { model: 'Land Cruiser',cat: 'suv_luxe'    },
    { model: 'Hilux',       cat: 'utilitaire'  },
    { model: 'GR Supra',    cat: 'sports'      },
    { model: 'GR86',        cat: 'sports'      },
    { model: 'bZ4X',        cat: 'electrique'  },
  ],
  Honda: [
    { model: 'Jazz',        cat: 'citadine'    },
    { model: 'Civic',       cat: 'berline'     },
    { model: 'CR-V',        cat: 'suv'         },
    { model: 'HR-V',        cat: 'suv_compact' },
    { model: 'e',           cat: 'electrique'  },
    { model: 'NSX',         cat: 'supercar'    },
  ],
  Nissan: [
    { model: 'Micra',       cat: 'citadine'    },
    { model: 'Juke',        cat: 'suv_compact' },
    { model: 'Qashqai',     cat: 'suv'         },
    { model: 'X-Trail',     cat: 'suv'         },
    { model: 'Leaf',        cat: 'electrique'  },
    { model: 'Ariya',       cat: 'electrique'  },
    { model: 'GT-R',        cat: 'supercar'    },
    { model: 'Navara',      cat: 'utilitaire'  },
  ],
  Hyundai: [
    { model: 'i10',         cat: 'citadine'    },
    { model: 'i20',         cat: 'citadine'    },
    { model: 'i30',         cat: 'berline'     },
    { model: 'Kona',        cat: 'suv_compact' },
    { model: 'Tucson',      cat: 'suv'         },
    { model: 'Santa Fe',    cat: 'suv_luxe'    },
    { model: 'Ioniq 5',     cat: 'electrique'  },
    { model: 'Ioniq 6',     cat: 'electrique'  },
    { model: 'NEXO',        cat: 'electrique'  },
  ],
  Kia: [
    { model: 'Picanto',     cat: 'citadine'    },
    { model: 'Rio',         cat: 'citadine'    },
    { model: 'Ceed',        cat: 'berline'     },
    { model: 'XCeed',       cat: 'suv_compact' },
    { model: 'Stinger',     cat: 'sports'      },
    { model: 'Sportage',    cat: 'suv'         },
    { model: 'Sorento',     cat: 'suv_luxe'    },
    { model: 'EV6',         cat: 'electrique'  },
    { model: 'EV9',         cat: 'electrique'  },
    { model: 'Niro',        cat: 'suv_compact' },
  ],
  Mazda: [
    { model: 'Mazda2',      cat: 'citadine'    },
    { model: 'Mazda3',      cat: 'berline'     },
    { model: 'Mazda6',      cat: 'berline_luxe'},
    { model: 'CX-3',        cat: 'suv_compact' },
    { model: 'CX-5',        cat: 'suv'         },
    { model: 'CX-60',       cat: 'suv_luxe'    },
    { model: 'MX-5',        cat: 'cabriolet'   },
    { model: 'MX-30',       cat: 'electrique'  },
  ],

  // ── USA ──────────────────────────────────────────────────────────────────────
  Tesla: [
    { model: 'Model 3',     cat: 'electrique'  },
    { model: 'Model S',     cat: 'electrique'  },
    { model: 'Model X',     cat: 'electrique'  },
    { model: 'Model Y',     cat: 'electrique'  },
    { model: 'Roadster',    cat: 'electrique'  },
    { model: 'Cybertruck',  cat: 'electrique'  },
  ],
  Ford: [
    { model: 'Fiesta',      cat: 'citadine'    },
    { model: 'Focus',       cat: 'berline'     },
    { model: 'Mondeo',      cat: 'berline_luxe'},
    { model: 'Puma',        cat: 'suv_compact' },
    { model: 'Kuga',        cat: 'suv'         },
    { model: 'Explorer',    cat: 'suv_luxe'    },
    { model: 'Mustang',     cat: 'sports'      },
    { model: 'Mustang Mach-E', cat: 'electrique'},
    { model: 'F-150',       cat: 'utilitaire'  },
    { model: 'Bronco',      cat: 'suv_luxe'    },
  ],
  Jeep: [
    { model: 'Renegade',    cat: 'suv_compact' },
    { model: 'Compass',     cat: 'suv_compact' },
    { model: 'Cherokee',    cat: 'suv'         },
    { model: 'Grand Cherokee', cat: 'suv_luxe' },
    { model: 'Wrangler',    cat: 'suv_luxe'    },
    { model: 'Gladiator',   cat: 'utilitaire'  },
  ],

  // ── UK ───────────────────────────────────────────────────────────────────────
  'Land Rover': [
    { model: 'Defender',    cat: 'suv_luxe'    },
    { model: 'Discovery',   cat: 'suv_luxe'    },
    { model: 'Discovery Sport', cat: 'suv'     },
    { model: 'Range Rover', cat: 'suv_luxe'    },
    { model: 'Range Rover Sport', cat: 'suv_luxe'},
    { model: 'Range Rover Evoque', cat: 'suv'  },
    { model: 'Range Rover Velar',  cat: 'suv_luxe'},
  ],
  Mini: [
    { model: '3-portes',    cat: 'citadine'    },
    { model: '5-portes',    cat: 'citadine'    },
    { model: 'Cabrio',      cat: 'cabriolet'   },
    { model: 'Clubman',     cat: 'berline'     },
    { model: 'Countryman',  cat: 'suv_compact' },
    { model: 'Paceman',     cat: 'suv_compact' },
    { model: 'John Cooper Works', cat: 'sports'},
    { model: 'Electric',    cat: 'electrique'  },
  ],
  Bentley: [
    { model: 'Continental GT',  cat: 'supercar'   },
    { model: 'Continental GTC', cat: 'cabriolet'  },
    { model: 'Bentayga',        cat: 'suv_luxe'   },
    { model: 'Flying Spur',     cat: 'berline_luxe'},
    { model: 'Mulsanne',        cat: 'berline_luxe'},
  ],
  'Rolls-Royce': [
    { model: 'Ghost',       cat: 'berline_luxe'},
    { model: 'Phantom',     cat: 'berline_luxe'},
    { model: 'Wraith',      cat: 'supercar'    },
    { model: 'Cullinan',    cat: 'suv_luxe'    },
    { model: 'Spectre',     cat: 'electrique'  },
  ],
  McLaren: [
    { model: '720S',        cat: 'supercar'    },
    { model: 'Artura',      cat: 'supercar'    },
    { model: 'GT',          cat: 'supercar'    },
    { model: 'Elva',        cat: 'supercar'    },
  ],

  // ── SUÈDE ────────────────────────────────────────────────────────────────────
  Volvo: [
    { model: 'V40',         cat: 'berline'     },
    { model: 'V60',         cat: 'berline'     },
    { model: 'V90',         cat: 'berline_luxe'},
    { model: 'S60',         cat: 'berline'     },
    { model: 'S90',         cat: 'berline_luxe'},
    { model: 'XC40',        cat: 'suv_compact' },
    { model: 'XC60',        cat: 'suv'         },
    { model: 'XC90',        cat: 'suv_luxe'    },
    { model: 'C40 Recharge',cat: 'electrique'  },
    { model: 'EX90',        cat: 'electrique'  },
  ],
}

/** Retourne la liste des marques triées */
export const MAKES = Object.keys(VEHICLE_CATALOG).sort()

/** Retourne les modèles d'une marque */
export function getModels(make) {
  return VEHICLE_CATALOG[make] || []
}

/** Retourne la catégorie d'un modèle donné */
export function getCategory(make, model) {
  const models = VEHICLE_CATALOG[make] || []
  const found = models.find(m => m.model.toLowerCase() === (model || '').toLowerCase())
  return found?.cat || null
}
